// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs.proto

package cs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// client  <-> server  10000 - 19999
type MessageCmd int32

const (
	MessageCmd_NULL  MessageCmd = 0
	MessageCmd_Login MessageCmd = 1
)

var MessageCmd_name = map[int32]string{
	0: "NULL",
	1: "Login",
}

var MessageCmd_value = map[string]int32{
	"NULL":  0,
	"Login": 1,
}

func (x MessageCmd) String() string {
	return proto.EnumName(MessageCmd_name, int32(x))
}

func (MessageCmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{0}
}

type ErrorCode int32

const (
	ErrorCode_OK ErrorCode = 0
)

var ErrorCode_name = map[int32]string{
	0: "OK",
}

var ErrorCode_value = map[string]int32{
	"OK": 0,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{1}
}

type Message struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	MsgType              int32    `protobuf:"varint,3,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Seq                  int32    `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Userdata             int32    `protobuf:"varint,5,opt,name=userdata,proto3" json:"userdata,omitempty"`
	Payload              []byte   `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *Message) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Message) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *Message) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Message) GetUserdata() int32 {
	if m != nil {
		return m.Userdata
	}
	return 0
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type LoginReq struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{1}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type Result struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LoginResp struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Passwd               string   `protobuf:"bytes,3,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{3}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *LoginResp) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginResp) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *LoginResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("cs.MessageCmd", MessageCmd_name, MessageCmd_value)
	proto.RegisterEnum("cs.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*Message)(nil), "cs.Message")
	proto.RegisterType((*LoginReq)(nil), "cs.LoginReq")
	proto.RegisterType((*Result)(nil), "cs.Result")
	proto.RegisterType((*LoginResp)(nil), "cs.LoginResp")
}

func init() { proto.RegisterFile("cs.proto", fileDescriptor_af7bf51985781725) }

var fileDescriptor_af7bf51985781725 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0xeb, 0xfc, 0x35, 0x99, 0xb2, 0x88, 0x8c, 0x84, 0x2c, 0x56, 0x21, 0xab, 0xa8, 0x8b,
	0x2c, 0x80, 0x1b, 0x54, 0xac, 0x08, 0x20, 0x59, 0x70, 0x00, 0x13, 0x5b, 0x51, 0xa4, 0xba, 0x4e,
	0x3d, 0x89, 0x50, 0x4f, 0xc1, 0x95, 0x91, 0xdd, 0x84, 0xb2, 0x60, 0xf7, 0xde, 0xb3, 0x67, 0xe6,
	0xf3, 0x18, 0xd2, 0x16, 0xeb, 0xc1, 0x9a, 0xd1, 0xd0, 0xa0, 0xc5, 0xf2, 0x9b, 0xc0, 0xfa, 0x45,
	0x21, 0x8a, 0x4e, 0xd1, 0x1c, 0xc2, 0x56, 0x4b, 0x46, 0x0a, 0x52, 0x65, 0xdc, 0x49, 0x97, 0x4c,
	0xbd, 0x64, 0xc1, 0x39, 0x99, 0x7a, 0x49, 0x19, 0xac, 0x35, 0x76, 0xef, 0xa7, 0x41, 0xb1, 0xb0,
	0x20, 0x55, 0xcc, 0x17, 0xeb, 0xee, 0xa2, 0x3a, 0xb2, 0xc8, 0xa7, 0x4e, 0xd2, 0x5b, 0x48, 0x27,
	0x54, 0x56, 0x8a, 0x51, 0xb0, 0xd8, 0xc7, 0xbf, 0xde, 0xf5, 0x19, 0xc4, 0x69, 0x6f, 0x84, 0x64,
	0x9b, 0x82, 0x54, 0x57, 0x7c, 0xb1, 0xe5, 0x23, 0xa4, 0x8d, 0xe9, 0xfa, 0x03, 0x57, 0xc7, 0x65,
	0x3e, 0xb9, 0xcc, 0xbf, 0x81, 0x64, 0x10, 0x88, 0x5f, 0x0b, 0xd4, 0xec, 0xca, 0x1a, 0x12, 0xae,
	0x70, 0xda, 0x8f, 0x94, 0x42, 0xd4, 0x1a, 0xa9, 0x7c, 0x51, 0xcc, 0xbd, 0x76, 0x7d, 0x34, 0x76,
	0xcb, 0x3b, 0x34, 0x76, 0xa5, 0x86, 0x6c, 0x9e, 0x82, 0x03, 0x2d, 0x21, 0xb1, 0xbe, 0xd8, 0x17,
	0x6d, 0xee, 0xa1, 0x6e, 0xb1, 0x3e, 0xb7, 0xe3, 0xf3, 0xc9, 0x3f, 0xab, 0xb8, 0xa0, 0x84, 0x7f,
	0x51, 0x1c, 0xc0, 0x41, 0x68, 0xe5, 0x37, 0x91, 0x71, 0xaf, 0xb7, 0x77, 0x00, 0xf3, 0x96, 0x77,
	0x5a, 0xd2, 0x14, 0xa2, 0xd7, 0x8f, 0xa6, 0xc9, 0x57, 0x34, 0x83, 0xd8, 0x63, 0xe4, 0x64, 0x7b,
	0x0d, 0xd9, 0x93, 0xb5, 0xc6, 0xee, 0x1c, 0x70, 0x02, 0xc1, 0xdb, 0x73, 0xbe, 0xfa, 0x4c, 0xfc,
	0x4f, 0x3d, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x63, 0xa1, 0x10, 0xb5, 0x01, 0x00, 0x00,
}
