name: gamedb0

log:
  filename: logs/server.log
  level: 7
  max_size: 1024
  max_lines: 100000
  hour_enabled: false
  daily_enabled: true
  queue_size: 1000

http:
  address: :11080
  queue_size: 1000

grpc:
  address: :14001
  max_conn_num: 1024
  socket_queue_size: 100
  max_message_size: 4096
  worker_pool_capacity: 128
  queue_size: 1000


mysql:
  worker_pool_capacity: 128
  queue_size: 1000
  nodes:
    - id: 0
      driver: mysql
      dsn: root:123456@tcp(127.0.0.1:3306)/game?charset=utf8&parseTime=True&loc=Asia%2FShanghai


logic:
  worker_pool_capacity: 128
  queue_size: 1000