name: gate0

log:
  filename: logs/server.log
  level: 7
  max_size: 1024
  max_lines: 100000
  hour_enabled: false
  daily_enabled: true
  queue_size: 1000

http:
  address: :11080
  queue_size: 1000

wsjson:
  address: :12080
  max_conn_num: 1024
  socket_queue_size: 100
  max_message_size: 4096
  http_timeout: 10
  cert_file:
  key_file:
  worker_pool_capacity: 128
  queue_size: 1000

wspb:
  address: :12080
  max_conn_num: 1024
  socket_queue_size: 100
  max_message_size: 4096
  http_timeout: 10
  cert_file:
  key_file:
  worker_pool_capacity: 128
  queue_size: 1000

grpc_client:
  conn_num: 1
  connect_interval: 3
  handshake_timeout: 10
  auto_reconnect: true
  max_message_size: 4096
  socket_queue_size: 100
  queue_size: 1000
  nodes:
    - id: 0
      name: logic0
      address: :14000

logic:
  worker_pool_capacity: 128
  queue_size: 1000