// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs.proto

package cs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	ID                   int32             `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Cmd                  string            `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	MsgType              int32             `protobuf:"varint,3,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Options              map[string][]byte `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Payload              []byte            `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Header) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *Header) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *Header) GetOptions() map[string][]byte {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Header) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "cs.Header")
	proto.RegisterMapType((map[string][]byte)(nil), "cs.Header.OptionsEntry")
}

func init() { proto.RegisterFile("cs.proto", fileDescriptor_af7bf51985781725) }

var fileDescriptor_af7bf51985781725 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x2e, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4a, 0x2e, 0x56, 0x3a, 0xcb, 0xc8, 0xc5, 0xe6, 0x91, 0x9a,
	0x98, 0x92, 0x5a, 0x24, 0xc4, 0xc7, 0xc5, 0xe4, 0xe9, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a,
	0xc4, 0xe4, 0xe9, 0x22, 0x24, 0xc0, 0xc5, 0x9c, 0x9c, 0x9b, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1,
	0x19, 0x04, 0x62, 0x0a, 0x49, 0x70, 0xb1, 0xe7, 0x16, 0xa7, 0x87, 0x54, 0x16, 0xa4, 0x4a, 0x30,
	0x83, 0x95, 0xc1, 0xb8, 0x42, 0x86, 0x5c, 0xec, 0xf9, 0x05, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x12,
	0x2c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xe2, 0x7a, 0xc9, 0xc5, 0x7a, 0x10, 0x83, 0xf5, 0xfc, 0x21,
	0x32, 0xae, 0x79, 0x25, 0x45, 0x95, 0x41, 0x30, 0x75, 0x20, 0xc3, 0x0a, 0x12, 0x2b, 0x73, 0xf2,
	0x13, 0x53, 0x24, 0xb8, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x29, 0x2b, 0x2e, 0x1e, 0x64,
	0x2d, 0x20, 0x87, 0x64, 0xa7, 0x56, 0x82, 0x5d, 0xc6, 0x19, 0x04, 0x62, 0x0a, 0x89, 0x70, 0xb1,
	0x96, 0x25, 0xe6, 0x94, 0xa6, 0x82, 0x1d, 0xc7, 0x13, 0x04, 0xe1, 0x58, 0x31, 0x59, 0x30, 0x26,
	0xb1, 0x81, 0xbd, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xec, 0x53, 0x39, 0xe6, 0x00,
	0x00, 0x00,
}
