host: localhost:11080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Nethopper Micro Server - Logic
  version: 1.0.2
paths:
  /call/LoginHandler:
    put:
      consumes:
      - text/plain
      parameters:
      - description: UserID
        in: query
        name: uid
        required: true
        type: string
      - description: Password
        in: query
        name: pwd
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: LoginHandler
      tags:
      - LogicModule
swagger: "2.0"
