name: simple_server

log:
  filename: server.log
  level: 7
  max_size: 1024
  max_lines: 100000
  hour_enabled: false
  daily_enabled: true
  queue_size: 1000

http:
  address: :11080
  queue_size: 1000

tcp:
  address: :15000
  max_conn_num: 1024
  socket_queue_size: 100
  max_message_size: 4096
  read_buffer_size: 32767
  write_buffer_size: 32767
  network: tcp4
  read_dead_line: 15
  worker_pool_capacity: 128
  queue_size: 1000

kcp:
  address: :14000
  max_conn_num: 1024
  socket_queue_size: 100
  max_message_size: 4096
  udp_socket_buffer: 4194304
  udp_snd_wnd: 32
  udp_recv_wnd: 32
  udp_mtu: 1280
  dscp: 46
  nodelay: 1
  interval: 20
  resend: 1
  nc: 1
  read_dead_line: 15
  worker_pool_capacity: 128
  queue_size: 1000

quic:
  address: :16000
  max_conn_num: 1024
  socket_queue_size: 100
  max_message_size: 4096
  read_buffer_size: 32767
  write_buffer_size: 32767
  network: quic4
  read_dead_line: 15
  worker_pool_capacity: 128
  queue_size: 1000

wsjson:
  address: :12080
  max_conn_num: 1024
  socket_queue_size: 100
  max_message_size: 4096
  http_timeout: 10
  cert_file:
  key_file:
  worker_pool_capacity: 128
  queue_size: 1000

wspb:
  address: :12080
  max_conn_num: 1024
  socket_queue_size: 100
  max_message_size: 4096
  http_timeout: 10
  cert_file:
  key_file:
  worker_pool_capacity: 128
  queue_size: 1000

grpc:
  address: :14000
  max_conn_num: 1024
  socket_queue_size: 100
  max_message_size: 4096
  worker_pool_capacity: 128
  queue_size: 1000

grpc_client:
  conn_num: 1
  connect_interval: 3
  handshake_timeout: 10
  auto_reconnect: true
  max_message_size: 4096
  socket_queue_size: 100
  queue_size: 1000
  nodes:
    - id: 0
      name: game1
      address: :14000

mysql:
  worker_pool_capacity: 128
  queue_size: 1000
  nodes:
    - id: 0
      driver: mysql
      dsn: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Asia%2FShanghai

redis:
  max_idle: 8
  max_active: 10
  idle_timeout: 300
  worker_pool_capacity: 128
  connect_interval: 3
  auto_reconnect: true
  queue_size: 1000
  nodes:
    - id: 0
      password:
      address: 127.0.0.1:6379
      db: 0

logic:
  worker_pool_capacity: 128
