name: usercenter0
id: 1

log:
  filename: logs/server.log
  level: 7
  max_size: 1024
  max_lines: 100000
  hour_enabled: false
  daily_enabled: true
  queue_size: 1000

http:
  address: :11080
  queue_size: 1000

grpc:
  address: :14000
  max_conn_num: 1024
  socket_queue_size: 100
  max_message_size: 4096
  worker_pool_capacity: 128
  queue_size: 1000

logic:
  worker_pool_capacity: 128
  queue_size: 1000

mysql:
  worker_pool_capacity: 128
  queue_size: 1000
  nodes:
    - id: 0
      driver: mysql
      dsn: root:123456@tcp(127.0.0.1:3306)/usercenter?charset=utf8&parseTime=True&loc=Asia%2FShanghai


redis:
  max_idle: 8
  max_active: 10
  idle_timeout: 300
  worker_pool_capacity: 128
  connect_interval: 3
  auto_reconnect: true
  queue_size: 1000
  nodes:
    - id: 0
      password:
      address: 127.0.0.1:6379
      db: 0

wx:
  queue_size: 100
  apps:
    - appid: wxec644f0c4e2cb275
      app_secret: ed2ff69a1575fb635eba2a03e9c304d6