name: simple_client

log:
  filename: logs/client.log
  level: 7
  max_size: 5000
  max_lines: 10000000
  hour_enabled: false
  daily_enabled: true
  queue_size: 1000

grpc_client:
  conn_num: 1
  connect_interval: 3
  handshake_timeout: 10
  auto_reconnect: true
  max_message_size: 4096
  socket_queue_size: 100
  queue_size: 1000
  nodes:
    - id: 0
      name: game1
      address: :14000

ws_client:
  conn_num: 1
  connect_interval: 3
  handshake_timeout: 10
  auto_reconnect: true
  max_message_size: 4096
  socket_queue_size: 100
  token: 12345678
  queue_size: 1000
  uid: 1
  nodes:
    - id: 0
      name: game1
      address: ws://127.0.0.1:12080

tcp_client:
  conn_num: 1
  connect_interval: 3
  handshake_timeout: 10
  auto_reconnect: true
  max_message_size: 4096
  socket_queue_size: 100
  network: tcp4
  token: 12345678
  uid: 1
  read_buffer_size: 32767
  write_buffer_size: 32767
  read_dead_line: 15
  queue_size: 1000
  nodes:
    - id: 0
      name: game1
      address: 127.0.0.1:12080

quic_client:
  conn_num: 1
  connect_interval: 3
  handshake_timeout: 10
  auto_reconnect: true
  max_message_size: 4096
  socket_queue_size: 100
  network: tcp4
  token: 12345678
  uid: 1
  read_buffer_size: 32767
  write_buffer_size: 32767
  read_dead_line: 15
  queue_size: 1000
  nodes:
    - id: 0
      name: game1
      address: 127.0.0.1:12080

kcp_client:
  conn_num: 1
  connect_interval: 3
  handshake_timeout: 10
  auto_reconnect: true
  max_message_size: 4096
  socket_queue_size: 100
  udp_socket_buffer_size: 4194304
  dscp: 46
  sndwnd: 32
  rcvwnd: 32
  mtu: 1280
  nodelay: 1
  interval: 20
  resend: 1
  nc: 1
  read_dead_line: 15
  token: 12345678
  uid: 1
  queue_size: 1000
  nodes:
    - id: 0
      name: game1
      address: 127.0.0.1:12080

logic:
  worker_pool_capacity: 128
  queue_size: 1000
